### ISSUE TITLE
Include all nodes of a path during mapping.

### ISSUE THREAD

**Issue by Jafeyyu** [spring-projects/spring-data-neo4j#2114]
https://github.com/spring-projects/spring-data-neo4j/blob/f18e15a6b899cdcdf719e1bc68e61c4c4a7d7d3d/src/main/java/org/springframework/data/neo4j/core/mapping/DefaultNeo4jEntityConverter.java#L487
The Nodes of Path need to filter should be PATH_START and PATH_END,but there is PATH_START and PATH_START

**Comment by michael-simons** [comment]
🤦 Oh dear.

Thank you so much.

**Comment by michael-simons** [comment]
There are a couple of scenarios where not all nodes or not all relationships of a path have been included in the mapping. First of call we filtered on the wrong path segment as documented by @Jafeyyu in this ticket and in some scenarios the synthesization of values did not include the segments in such a way that everything in the result was actually used in the mapping.

This is fixed by synthesizing a result that has the form as a custom query (root node, all relationships and all related nodes), instead of going through the paths.

**Comment by Jafeyyu** [comment]
I think you are right, I thought so before, but I don't know how to describe it, because my English is not very good, because of this problem, I put the version at 5.6.3 in my project,Thank you for fixed it

**Comment by michael-simons** [comment]
No worries, your contribution is appreciated, I wouldn't have the issue so soon without it. Take care!
