### ISSUE TITLE
How to create relationship between two exists Nodes

### ISSUE THREAD

**Issue by wurangbo** [spring-projects/spring-data-neo4j#2338]
Hi Guys, I want  to create relationship between two exists Nodes, How can I define the relationship class ?

```
@Node("DeviceNode")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class DeviceNode {
    @Id
    @GeneratedValue
    private Long id;

    private Integer deviceId;

    private String deviceName;

    private Integer deviceCategoryId;

    private String deviceCategoryName;

    private AlarmState alarmState;
}
```

**Comment by meistermeier** [comment]
Assuming you have already a `DeviceNodeRepository` and a `AlarmStateRepository` like this
```
public interface DeviceNodeRepository extends Neo4jRepository<DeviceNode, Long> {}
```

You would fetch both entities and add the `AlarmState` to the `DeviceNode` and call `deviceRespository.save(deviceNode)`.
A few things to notice here:
1. You could also explicitly add `@Relationship("relationship_type")` to the relationships.
2. From a Spring Data perspective it is now advised to create repositories for each entity/node but handle those as an aggregate. So you would either define the `AlarmState` already at node creation or add a new one to it instead of an already existing one. I know that reality differs sometimes and this is not possible all the time, but please keep this in mind.

I am closing this issue right now because it is not an issue with the library itself as far as I can see.
A better place to ask those questions is either our forum at https://community.neo4j.com/c/drivers-stacks/spring-data-neo4j-ogm/30 or StackOverflow https://stackoverflow.com/questions/tagged/spring-data-neo4j
