### ISSUE TITLE
Run query in transaction using Neo4jClient

### ISSUE THREAD

**Issue by alxxyz** [spring-projects/spring-data-neo4j#2396]
Currently we a using `Neo4jClient` class and `query` method to prepare the query and execute `fetch` after preparation
```
neo4jClient.query("...")
                .bindAll(parameters)
                .fetch()
                .all().stream()
                .collect(Collectors.toList())
```
How we can execute this code in a neo4j transaction?

**Comment by meistermeier** [comment]
Those operations already run within a Neo4j driver connection. Could you me more precise?

**Comment by michael-simons** [comment]
If this runs in a Spring transaction (Either with `@Transactional` annotated or explicit inside a call to `TransactionTemplate` or `TransactionalOperator` (in the case of reactive)), it will participate in Spring transactions, otherwise it will open up a native Neo4j transaction and close it afterwards, see:

![sdn-buildingblocks](https://user-images.githubusercontent.com/526383/136156331-bbdf9e57-94dc-45d0-98e9-7de5fef7d8f5.png)

https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#building-blocks
