### ISSUE TITLE
Instantiation issue for abstract type when query contains descendent types

### ISSUE THREAD

**Issue by LogicGateDan** [spring-projects/spring-data-neo4j#2401]
[This simple example](https://github.com/LogicGateDan/sdn-repository-bug) demonstrates what appears to be unexpected behavior in SDN when attempting to use a repository
based on an abstract super-class domain entity to query results that should return objects of descendent domain class 
types.

The project has three domain classes; one abstract super-class, `Person`, and two descendent classes, `EvilPerson` 
and `GoodPerson`. The classes are organized as follows:

- Person
  - GoodPerson extends Person
  - EvilPerson extends Person

Rather than creating a repository interface for each of the descendent domain entities, it would be desirable to create
a single repository for the parent class. Although this is a contrived example, the value of setting things up this way
would be readily apparent in scenarios where there were a large number of descendent class types and the majority of
queries would be across all of those types instead of across a specific sub-type.

However, without creating repositories for `GoodPerson` and `EvilPerson`, queries against the `PersonRepository` will fail when it's used to query data that wasn't persisted through the repository itself. The linked sample project explains this in more detail and provides example tests to illustrate the point.

**Comment by meistermeier** [comment]
The problem with your configuration in combination with the repository definition for the abstract entity is, that you do not provide an initial set of entities for SDN to work with.
You could fix this by adding:
```
@Override
protected Collection<String> getMappingBasePackages() {
  return Collections.singleton(Person.class.getPackageName());
}
```
to your `Neo4jConfig` (yes, this could be a little bit more elegant but you hopefully get the idea).
With this, SDN will pre-populate the mapping context with not only `Person`, that is known by the repository definition, but also `GoodPerson` and `EvilPerson`. With scanning all classes  Spring Data Neo4j can also make sense of the hierarchy. Otherwise it will only know about the explicit referenced entities (in your case `Person`).

Bonus information:
there is also a Spring Boot autoconfiguration in place for the Neo4j driver and Spring Data Neo4j
```
spring:
  neo4j:
    security:
      trust-strategy: trust_all_certificates
      hostname-verification-enabled: false
    authentication:
      username: neo4j
      password: secret
    uri: neo4j://localhost:7687
```
and all the other known configuration parameters of the Java driver are available without the need to define an additional dependency.
You would also benefit from an autoconfigured Spring Data Neo4j that would scan for entities starting at the `@Configuration` level as default.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
