### ISSUE TITLE
Composite property: reading neo4j wrapper objects instead of java primitives

### ISSUE THREAD

**Issue by gonzalad** [spring-projects/spring-data-neo4j#2450]
Hello,

I'm not sure this is an issue or not (it could be an enhancement), anyway, here it is:
When I store a string in a composite property, I'd expect to retrieve a string when reading the database.
But instead i get a wrapper object (StringValue). 

I could implement my own compositeProperty converter, but should this use case (simple type management) be handled by default ?

This issue can be reproduced with https://github.com/gonzalad/sdn6-tests/tree/issue-composite-properties (run this unit test https://github.com/gonzalad/sdn6-tests/blob/issue-composite-properties/src/test/java/com/example/sdn6/Sdn6Test.java#L49)

Thanks,

**Comment by michael-simons** [comment]
Hi @gonzalad 

This is a behavior intentionally by design. As you defined your composite property in the most generic way like this:

```java
@CompositeProperty(prefix = "somePrefix")
private Map<String, Object> composite = new HashMap<>();
```

we can determine what kind the value is during _writing_ but we can only *guess* what you want when _reading_. Do you want a `String` or a `Long` with a value such as `42`? 

You might argue that you wrote `(Long) 42` initially and that there's an integer property in the database at that point, but that doesn't need to be uniform by label.

If you always have Strings in that map, please define the attribute in the class like this:

```java
private Map<String, String> composite = new HashMap<>();
```

and your test will work as expected:

```java
@Test
void givenCompositePropertyWithStringEntryWhenQueryThenVerifyReturnsStringInstance() {

    Map composite = new HashMap(Map.ofEntries(
        Map.entry("entry1", "value1"),
        Map.entry("entry2", "value2")
    ));
    SampleEntity entity = createSample(composite);
    sampleRepository.save(entity);

    Optional<SampleEntity> entityInDatabase = sampleRepository.findById(entity.getId());

    assertThat(entityInDatabase).isPresent();
    assertThat(entityInDatabase.orElseThrow().getComposite().get("entry2")).isEqualTo("value2");
}

/**
 * This test works (just to check basic composite property usage)
 */
@Test
void testUpdateEntryInCompositeProperty() {

    Map composite = new HashMap(Map.ofEntries(
        Map.entry("entry1", "value1"),
        Map.entry("entry2", "value2")
    ));
    SampleEntity entity = createSample(composite);
    assertThat(entity.getComposite()).hasSize(2);
    entity.getComposite().put("entry2", "change");
    sampleRepository.save(entity);

    Optional<SampleEntity> entityInDatabase = sampleRepository.findById(entity.getId());

    assertThat(entityInDatabase).isPresent();
    assertThat(entityInDatabase.orElseThrow().getComposite().get("entry2"))
        //.extracting(v -> ((Value) v).asString())
        .isEqualTo("change");
}
```

Otherwise, please run a custom converter and judge on a case by case (i.e. depending on the key) what kind of value you want.

You find a couple of samples here: https://github.com/spring-projects/spring-data-neo4j/blob/main/src/test/java/org/springframework/data/neo4j/integration/shared/conversion/ThingWithCompositeProperties.java
