### ISSUE TITLE
Hydratation of object relationships using path

### ISSUE THREAD

**Issue by paulux84** [spring-projects/spring-data-neo4j#2473]
Hi, 
I've created a query inside the repository to return a node with its nearest nodes, but only one of the relationships was marshalled inside returning object.
The query is the following: 

```
    @Query("MATCH p=(n:Place)-[:HAS_SERVICE]->(:Service) WHERE NOT $date IN n.lockedDates " +
            "AND NOT EXISTS((:Order{date:$date})-[:TAKES_PLACE]->(n)) " +
            "RETURN p")
    List<Place> findPlaceFreeOnDate(LocalDate date);
```

spring-data-neo4j version 6.2.2-GH-2470-SNAPSHOT
Thanks

**Comment by meistermeier** [comment]
Short version: I think what you are looking for is [Path return patterns](https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#custom-query.paths).
So your return pattern should be something like: `RETURN n, collect(nodes(p)), collect(relationships(p))`.

Longer version:
Spring Data Neo4j works completely record/row oriented. There are some exceptions to the rule when we detect an already mapped object within the same result set (result = sum of all returned records) where we try to re-use the very same instance if possible.
What happens in your case:
```
class A {
    @Relationship("LINKED_TO") List<B> bs;
}
```
Would return with the query `MATCH p=(:A)-[:LINKED_TO]->(:B) return p` and let's say three `B`s:
```
A1 | B1
A1 | B2
A1 | B3
```
But SDN already has hydrated `A1` and would not touch the `bs` list. Also this would be somehow wrong because we would get very far away from the record-focused mapping approach and now manipulate objects in some "future"/later mapping runs instead of just re-using them.

Please let me know if this works for you.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by paulux84** [comment]
Thanks for reply...now is clear

**Comment by meistermeier** [comment]
Thanks for the feedback. Good to hear that it worked out in the end.
