### ISSUE TITLE
StackOverflowException with custom query and result contains circular references

### ISSUE THREAD

**Issue by gonzalad** [spring-projects/spring-data-neo4j#2514]
Hello,

I'm getting a StackOverflowException when executing a custom query and whent the result contains circular references.
I'm having this issue with SDN 6.2.3 (and 6.1.10).
I didn't have this issue in 6.1.5.

Since SDN works record-oriented I would expected to have some lines with duplicated entity instances (different instances, but same data), but I wouldn't have expected the stackOverflowException.

My entites:

```
@Node(labels = "Type")
public class Type {

    @Id
    @GeneratedValue
    private Long id;
    private String code;
    @Relationship(type = "IS_ALLOWED")
    private List<Type> allowed = new ArrayList<>();

   // getters/setters ommited
}
```

My repository:

```
@Repository
public interface TypeRepository extends Neo4jRepository<Type, Long> {

    @Query("MATCH (nt:Type)\n"
            + "OPTIONAL MATCH (nt)-[raut:IS_ALLOWED]->(aut)\n"
            + "RETURN nt,\n"
            + "  collect(raut), collect(aut)\n"
    )
    List<Type> findAllTypes();
}
```

And my unit test reproducing the error:

```
    @Test
    void findWithCircularReferenceThrowsStackOverflowException() {
        Type formation = new Type().code("FORMATION");
        Type groupement = new Type().code("GROUPEMENT");
        formation.allowed(groupement);
        groupement.allowed(groupement);
        List<Type> toSave = List.of(
                formation,
                groupement
        );
        repository.saveAll(toSave);

        List<Type> types = repository.findAllTypes();

        assertThat(types).isNotEmpty();
    }
```

The unit test is also available here: https://github.com/gonzalad/sdn-circular-references-stackoverflow/blob/master/src/test/java/com/example/sdncircularreferencesstackoverflow/SdnTest.java

Thanks for your help !

**Comment by meistermeier** [comment]
Thanks for reporting this. Interesting bit on this issue is that it depends on the order of entities coming from the database. If you are interested, you can try it out yourself and change the order of the list-to-save that `groupement` is the first entity. My version of Neo4j will return them ordered by id (no guarantee, but it works reproducible).
I can reproduce it also in the current development branches.
Some background on this regression(?): it goes hand in hand with a bug fix related to entity population that ensured objects will get the possibility to update their properties incl. relationships if they are not `final`.
Even though SDN works record oriented, there were some corner cases in which an already populated entity needed to get modified again.

**Comment by meistermeier** [comment]
There are now snapshot versions available.
`6.1.11-SNAPSHOT` and `6.2.4-SNAPSHOT` for the released versions.
`6.3.0-SNAPSHOT` and `7.0.0-SNAPSHOT` pre-release.
I have tested your reproducer with `6.2.4-SNAPSHOT` and it passed. Would be good to get your input also on this.

**Comment by michael-simons** [comment]
Thank you for providing us with great reproducers and feedback! This is contribution to OSS, too.
