### ISSUE TITLE
Wrong type of node instantiated causing ClassCastException

### ISSUE THREAD

**Issue by cberes** [spring-projects/spring-data-neo4j#2530]
SDN 6.2.4 may instantiate the wrong type of node under certain circumstances.

I have an [example repo](https://github.com/cberes/sdn-interface-node-bug) but here is a summary of the problem.

For example, say you have this weird type hierarchy

    @Node
    public abstract class Animal {
    }

    @Node
    public interface Cat {
    }

    // No Node annotation!
    public class DomesticCat extends Animal implements Cat {
    }

    @Node
    public class Tiger extends Animal implements Cat {
    }

If you save and query for a `Tiger`, then save and query for a `DomesticCat`, the second node will be a `Tiger` instead

    Tiger tiger = new tiger();
    animalRepository.save(tiger);

    Tiger found1 = (Tiger) animalRepository.findById(tiger.getId()).get();

    DomesticCat cat = new DomesticCat();
    animalRepository.save(cat);

    // ClassCastException: found2 is a Tiger
    DomesticCat found2 = (DomesticCat) animalRepository.findById(cat.getId()).get();

If you add `@Node` to `DomesticCat` or save and query in a different order, there are no errors.

This example worked correctly in SDN 6.2.1 but it fails with SDN 6.2.4.

**Comment by meistermeier** [comment]
Good observation and thanks for pointing this out.
I won't consider this as a bug because you have hit a scenario that is the result of Spring Boot auto-configuration and SDN's lazy registration of eligible entities.
If you start your application with no manual bean configuration, Spring Boot will configure the initial entities based on the explicitly `@Node` annotated classes. Those will be collected and passed over to the configuration (`initialEntitySet`) of the `Neo4jMappingContext`. This is the basic knowledge SDN will start to work with.
Only the moment, you are saving the `DomesticCat`, SDN will register the non-annotated entity as an additional option. This is the reason why changing the order also makes your test run green.
I hope it makes sense for you, if you have any questions, feel free to let us dig deeper into the topic, otherwise also feel free to close this issue.

**Comment by cberes** [comment]
thanks for looking into this. If I understand correctly, my organization is already using manual bean configuration but we are seeing this bug. I wonder if there is a bug in Neo4jEntityScanner. It doesn't seem to find all available entities. For example I added this configuration to my example project

	@Configuration
	public class Neo4jConfig extends AbstractNeo4jConfig {

	  @Override
	  protected Collection<String> getMappingBasePackages() {
		return List.of("com.example.sdnbug");
	  }

	  @Override
	  public Driver driver() {
		Config config = Config.builder().withoutEncryption().build();
		AuthToken authToken = AuthTokens.basic("neo4j", "neo4j");

		return GraphDatabase.driver("bolt://localhost:7687", authToken, config);
	  }

	  @Bean
	  @Override
	  protected DatabaseSelectionProvider databaseSelectionProvider() {
		return () -> DatabaseSelection.byName("db");
	  }
	}

When I put a breakpoint in Neo4jConfigurationSupport.getInitialEntitySet, I see that `Neo4jEntityScanner.get().scan(getMappingBasePackages())` finds only 1 entity (`Tiger`), when there should be 2 (`Tiger` and `DomesticCat`).

**Comment by meistermeier** [comment]
The `Neo4jEntityScanner` does exactly what I have explained in my previous comment. For a bunch of classes it looks for the `@Node` annotated ones. Otherwise automatic scans, like the one that got triggered by Spring Boot, would discover _all_ classes as -at least- candidates for entity registration.
If you are sure that all classes that you pass over should get scanned as entities, you could overwrite this method in your configuration: https://github.com/spring-projects/spring-data-neo4j/blob/72869e7d29044a06756fffcc8bcd6a2aecd50380/src/main/java/org/springframework/data/neo4j/config/Neo4jConfigurationSupport.java#L51-L58

**Comment by cberes** [comment]
Thanks! I was able to test this version, it does appear to pass intermittently now, around half of the time. Though it does seem to have some kind of race condition happening since it will still sporadically fail.

**Comment by meistermeier** [comment]
That's odd. Did you change something other than the dependencies? I tried to make it fail but it kept passing for 1000 runs.

**Comment by cberes** [comment]
Sounds good. If I'm able to reproduce the intermittent failures in an example project I'll open a follow up. Thanks for looking into this.
