### ISSUE TITLE
Add New Relation, Remove Existing Relation

### ISSUE THREAD

**Issue by dilipdhankecha2530** [spring-projects/spring-data-neo4j#2551]
While adding new relationship, the old relation is removed.

Expected behaviour,
Not remove the relationship and add new one.

**Comment by meistermeier** [comment]
This is expected behaviour to happen if you do not load the entity completely.
Expected usage: Load either the reachable graph for this object (https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#query-creation.save) or use a projection for loading and/or persisting your data: https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#projections.sdn.multi-level

**Comment by jmbarroso** [comment]
@meistermeier we are experiencing something similar. Is there any example we can check how to model nodes and relationships? ; what you are sharing as expected behavior seems confusing and I'm not sure what is the right pattern to model and save data.

**Comment by dilipdhankecha2530** [comment]
@meistermeier 

Do you have an example or anything from where we can get the idea about the projection concept.

**Comment by meistermeier** [comment]
I think this is a good integration test to get the idea:
https://github.com/spring-projects/spring-data-neo4j/blob/10e0f8610a87d07868cd6c4b960409ddf9bacbc9/src/test/java/org/springframework/data/neo4j/integration/movies/imperative/AdvancedMappingIT.java

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
