### ISSUE TITLE
Polymorphism: relationships not populated for subtypes

### ISSUE THREAD

**Issue by ddoppmeier** [spring-projects/spring-data-neo4j#2639]
Hi everybody!

I'm experiencing problems loading lists of related objects when polymorphism is involved.

### The data model:
`Company` references its employees by their common `Person` supertype.  
The implementations of `Person` are`Sales` and `Developer`.
`Developer` references a list of `Language`.  
(see below for simplified classes)

### Data retrieval
Data initially is stored using a `CompanyRepository extends Neo4jRepository<Company, Long>`.
Looking into Neo4j Browser reveals nothing unusual and everything seems fine.
But when querying for companies by `Company findByName(String name);` the returned developers have an empty List `programmingLanguages`.

### Versions used

- spring-boot-starter-parent 2.7.6
- spring-boot-starter-data-neo4j 6.3.6
- java oracle openjdk 19.0.1
- neo4j 4.4.10-enterprise

### Example implementation
[acme-corp.zip](https://github.com/spring-projects/spring-data-neo4j/files/10186721/acme-corp.zip)

### Classes (simplified)
```java
@Node
public class Company {

	@Id
	@GeneratedValue
	private Long id;
	private final String name;
	@Relationship(type = "EMPLOYEE")
	private final List<Person> employees;

	public Company(String name, List<Person> employees) {
		this.name = name;
		this.employees = employees;
	}
}
```

```java
@Node
public abstract class Person {

	@Id
	@GeneratedValue
	private Long id;

}
```

```java
@Node
public class Sales extends Person {

	private final String name;

	public Sales(String name) {
		this.name = name;
	}

}
```

```java
@Node
public class Developer extends Person {

	private final List<Language> programmingLanguages;
	private final String name;

	public Developer(String name, List<Language> programmingLanguages) {
		this.name = name;
		this.programmingLanguages = programmingLanguages;
	}

}
```

**Comment by meistermeier** [comment]
Thanks for the report. A first glance shows that the problem is somewhere between query generator and mapper.
SDN will try its best to gather all fields from the extending classes (in this case `Developer`) but only knows about the `Person` as the field. This leads to the situation that the naming of the returned list for the languages is wrong or the detection algorithm does not pick this up with the right prefix.
I will investigate this in more detail tomorrow. What surprises me is that this is a problem, we solved a long time ago. And your inheritance chain is far from being complex.

**Comment by meistermeier** [comment]
I have now a branch with a not-yet clean patch (issue/gh-2639).
This should create a snapshot release in ~30 minutes (from this post timestamp on 😄 ) for you to check out with your example or project.
To make use of it, define Spring's snapshot (and milestone) repository and the Spring Data Neo4j version explicitly.

```
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-neo4j</artifactId>
    <version>6.3.7-GH-2639-SNAPSHOT</version>
</dependency>
```
```
<repositories>
  <repository>
    <id>spring-milestones</id>
    <name>Spring Milestones</name>
    <url>https://repo.spring.io/milestone</url>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
  </repository>
  <repository>
    <id>spring-snapshots</id>
    <name>Spring Snapshots</name>
    <url>https://repo.spring.io/snapshot</url>
    <releases>
      <enabled>false</enabled>
    </releases>
  </repository>
</repositories>
```

**Comment by meistermeier** [comment]
Thanks for your fast feedback on the changes.
Yes, take your time and challenge us with your domain model 😁 
In more details: 
The problem in detail is _not_ that `Company` has `Persons` in general. But the deeper relationship mapping will only look for something like `Developers_ProgrammingLanguages` in the result, because SDN knows / did not know at this point that the definition for the result in the query creation was named `Person_ProgrammingLanguage`. That's because we collect all fields of the defined type and all its sub-types under the name of the defined type _not_ the concrete property/relationship defining sub-type. This originates from a former bug fix.

**Comment by meistermeier** [comment]
Thanks! I missed one spot for the abstraction detection.
A new snapshot with also this fix in place should be available in (you guessed it) ~30 minutes.
