### ISSUE TITLE
Getting warning about the deprecated id() function when using the @Id annotation.

### ISSUE THREAD

**Issue by subhankardas** [spring-projects/spring-data-neo4j#2716]
I am using the Neo4jRepository and @Node entity with @Id and @Relationship to another node entity and getting an error saying:
`023-05-02 00:59:57.789  WARN 17384 --- [           main] org.springframework.data.neo4j.cypher    : Neo.ClientNotification.Statement.FeatureDeprecationWarning: This feature is deprecated and will be removed in future versions.
        OPTIONAL MATCH (hlp:`Customer`) WHERE id(hlp) = $__id__ WITH hlp WHERE hlp IS NULL CREATE (customer:`Customer`) SET customer = $__properties__ RETURN customer UNION MATCH (customer:`Customer`) WHERE id(customer) = $__id__ SET customer += $__properties__ RETURN customer
                                              ^
The query used a deprecated function. ('id' is no longer supported)`
I am assuming this is due to the @Id annotation which is internally using deprecated function, so is there any planned release for this fix?

**Comment by meistermeier** [comment]
The `id` function for nodes and relationships got deprecated and was replaced with `elementId` in Neo4j 5. The warning itself just got _harsher_ with Neo4j 5.6 (and should not mention `..no longer supported..` in one of the next minor releases). There is nothing to worry about right now. It's just the message not any misbehaving functionality in Spring Data Neo4j.
We are internally working on making use of `elementId` already but couldn't do it for Spring Data Neo4j 7 back in the days because Neo4j 5 got released later and the feature was not stable.
If you want to keep the warnings for Cypher enabled but mute those messages, here is a solution to do this: https://github.com/spring-projects/spring-data-neo4j/issues/2660#issuecomment-1396698973
If you have any further questions regarding this topic, please reopen this issue.

**Comment by subhankardas** [comment]
Thanks for the help @meistermeier! :)

**Comment by nkonev** [comment]
```
import org.neo4j.cypherdsl.core.renderer.Configuration;
import org.neo4j.cypherdsl.core.renderer.Dialect;
...
    @Bean
    Configuration cypherDslConfiguration() {
        return Configuration.newConfig().withDialect(Dialect.NEO4J_5).build();
    }
```

helped to eliminate the warning. From [here](https://github.com/meistermeier/spring-graphql-neo4j/blob/be65c00/src/main/java/com/meistermeier/neo4j/graphql/Neo4jGraphqlApplication.java#L19).

**Comment by Zaidtech** [comment]
@meistermeier Why was the need introduced to switch from **id** to **elementId** ? Just was curious!

**Comment by meistermeier** [comment]
@Zaidtech Spring Data Neo4j just supports this new identifier type. The warnings, you are observing are coming directly from the database (Cypher) and are passed through to SDN. We did not introduce this but want our users to have support for (legacy) id and elementId without any breaking API.
Looking in the official reference documentation of Neo4j, you can see that the `id` function could create some problems with composite databases. Second green information box: https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-id
There were already some more improvements around the logging to make it easier muting unwanted categories: https://docs.spring.io/spring-data/neo4j/reference/appendix/logging.html
