### ISSUE TITLE
@RelationshipProperties for Dynamic Relationships

### ISSUE THREAD

**Issue by Kanish2002** [spring-projects/spring-data-neo4j#2820]
while creating a Dynamic Relationship using Map<String,AnnotatedDomainClass> there is only a way to name the TYPE of the Relationship like Person -KNOWS-> Person but no way to define relationship properties.

**Comment by meistermeier** [comment]
You could provide the `relationship properties-annotated` class instead of the `AnnotatedDomainClass` in the definition. Like here:
https://github.com/spring-projects/spring-data-neo4j/blob/47feb15244b6614cf173fedcb1ef7e392b4ccfe6/src/test/java/org/springframework/data/neo4j/integration/shared/common/PersonWithRelatives.java#L98-L100
Or I got you question wrong.

**Comment by Kanish2002** [comment]
Hi @meistermeier, Actually I got some java.reflect based exception while trying to done it, now it got resolved...
Got the answer for the question,
Thanks.
