### ISSUE TITLE
Persistence of One To Many Relationships / Collections via Projections does not delete removed relationships

### ISSUE THREAD

**Issue by NilsWild** [spring-projects/spring-data-neo4j#2883]
The [documentation](https://docs.spring.io/spring-data/neo4j/reference/projections/sdn-projections.html#projections.sdn.persistence) about persisting projections says: "To prevent deletion of data (e.g. removal of relationships), you should always load at least all the data that should get persisted later." So i expected that if a node is not present in the collection of a property of an entity and that property is present in the projection, the relationship gets deleted. However, thats not the case as shown here: https://github.com/NilsWild/spring-issue-demo/tree/52c4354b994d090a9af4c7646cb4cecdff6071a4. Instead existing nodes get updated and new ones get created but missing ones do not get deleted.

So I think either this is a bug or the documentation is misleading.

**Comment by meistermeier** [comment]
In your example, you are using a custom id value. Which is (very) fine, but as a consequence requires the introduction of a `@Version` property to keep track of the state of the entity.
Your tests fail because SDN assumes that the entity `A` is new in both save operations and skips the deletion step because it is only needed if the entity is not new.
```
@Version
var version: Long? = null
```
would already fix your case.

for references:
Business keys: https://docs.spring.io/spring-data/neo4j/reference/object-mapping/mapping-ids.html#mapping.id-handling.business-key
Version property: https://docs.spring.io/spring-data/neo4j/reference/object-mapping/metadata-based-mapping.html#mapping.annotations.version

**Comment by NilsWild** [comment]
Thank you for pointing that out. My bad.
