### ISSUE TITLE
Nested object mapping for custom CYPHER query cut off since SDN 7.3.2

### ISSUE THREAD

**Issue by ruempel** [spring-projects/spring-data-neo4j#2963]
We are heavily using custom CYPHER queries in CRUD repositories for performance reasons.

Since SDN `7.3.2`, nested objects queried by relations are not mapped anymore. It worked until SDN `7.3.1`.

If you use this custom query, the `nested` object is `null` now:

```java
public interface MyRepository extends CrudRepository<MyModel, String> {

    @Query("""
            MATCH (root:MyModel {uuid: $uuid})
            RETURN root {
                     .*, MyModel_REL_TO_MY_NESTED_MODEL_MyModel: [
                       (root)-[:REL_TO_MY_NESTED_MODEL]->(nested:MyModel) | nested {. *}
                     ]
                   }
            """)
    Optional<MyModel> getByUuidCustomQuery(String uuid);
}
```
For your convenience, I prepared a minimum example Git repo with a test case, where you can try it out: https://github.com/planyverse/sdn-example

**Comment by michael-simons** [comment]
Hello @ruempel Thanks a lot for your report. This is a regression directly related to #2918 The fixed by @ma-ku adds the direction to the collection name, and I didn't spot the use case of custom queries when merging it, my bad, sorry. 

I am working on a fix that does not require changes on your side. Until this is available, you would be able to fix it by adding `true` for the outgoing relationship to the query:

```java
public interface MyRepository extends CrudRepository<MyModel, String> {

    @Query("""
            MATCH (root:MyModel {uuid: $uuid})
            RETURN root {
                     .*, MyModel_REL_TO_MY_NESTED_MODEL_MyModel_true: [
                       (root)-[:REL_TO_MY_NESTED_MODEL]->(nested:MyModel) | nested {. *}
                     ]
                   }
            """)
    Optional<MyModel> getByUuidCustomQuery(String uuid);
}
``` 

or `false`, if it is incoming.

**Comment by michael-simons** [comment]
(Excellent reproducer and bisection, thank you for that!)
