### ISSUE TITLE
Sometimes relations get lost in SDN4

### ISSUE THREAD

**Issue by nd0** [spring-projects/spring-data-neo4j#298]
I am testing against SDN4 4.0.0-BUILD-SNAPSHOT with neo4j-ogm version 1.1.0

If I create an Entity with relations to two other Entities
and save them with depth 1, everything is OK.

Next I load the entity and then the related entities seperatly.

If I set the related entites to the main entity and store the main entity with depth 1,
then one of related entities gets lost.

**Comment by luanne** [comment]
What does the entity and its relations look like? If you have a test case, that would be even more helpful

**Comment by monowai** [comment]
I’ve since re-written it to make it work by incorporating the @Relationship in both entities. My current work load is rather large on this migration, so it will take some time for me to get back to duplicating this.

The scenario was that fromEntity existed and had no @Relationship properties. The toEntity was new and needed to be persisted.

Under SDN3 the fromEntity had no properties and the toEntity was annotated as:
    @RelatedToVia(type = "LOGGED", direction = Direction.INCOMING)
    private EntityLogRelationship entityLog; // Many to one

To make it work under SDN4 I had to annotate the relationship in both entities 
   @Relationship(type = "LOGGED", direction = Relationship.INCOMING) // outgoing for the fromEntity
    Set<EntityLog> entityLogs = new HashSet<>();

So I guess it’s down to the many to one mapping.

**Comment by nd0** [comment]
Thanks for your quick response, I hoped, that you are already aware of this behavior.

Here comes a (not working) sample code,
I will try to strip down the the scenario to a test case.

```
public abstract class Entity {
  @GraphId
  private Long nodeId;
}

class EntityA extends Entity {
  @Relationship(type = "HAS")
  private Category category;
  
  @Relationship(type = "HAS")
  private Set<Hashtag> tags = new HashSet<Hashtag>();
}

public class Hashtag extends Entity {
    private String name;

    @Relationship(type = "HAS", direction = Relationship.INCOMING)
    private Set<Entity> entities = new HashSet<Entity>();
}

public class Category extends Entity {
    private String name;

    @Relationship(type = "HAS", direction = Relationship.INCOMING)
    private Set<Happening> happenings;
}
```

Create a new entity
```
List<String> tagNames = Arrays.asList("tag1", "tag2");

EntityA entity = new EntityA();
entity.setCategory(new Category("name"));
Set<Hashtag> tags = createHashtags(tagNames);
entity.setTags(tags);
entity = repository.save(entity, 1);
```

Update the entity, but use the same relations
```
EntityA entity = repository.find(entity.getNodeId());
Category category = categoryRepository.findByName("name");
Set<Hashtag> tags = hashtagService.findByNames(tagNames);
entity.setCategory(category);
entity.setTags(tags);
repository.save(entity, 1);
```
-> now all relations to the tags are gone

**Comment by luanne** [comment]
Moved to https://jira.spring.io/browse/DATAGRAPH-690
