### ISSUE TITLE
Date migration from SDN 3.4

### ISSUE THREAD

**Issue by nayish** [spring-projects/spring-data-neo4j#314]
In SDN 3.4 Date were saved to the db as Strings consisting of the number of miiseconds since 1970. In SDN 4.0 the String needs to by default contain a string representing the date in a format of "YYYY-MM-dd...." In the migration guide there is no mention of this change.

In addition using the @DateLong annotation which should correlate to the previous use throws an error since dates are saved in the DB as Strings and not numbers. after performing "SET a.dateField = toInt(a.dateField)" on all my dateFields this is solved.

This should either be added to the migration guide or perhaps fixed.

**Comment by luanne** [comment]
Thanks for reporting this, docs updated. See https://jira.spring.io/browse/DATAGRAPH-765

**Comment by nayish** [comment]
Is there a reason that Dates are now defaulted to String value and not long. It seems bad practice since it would be hard to sort and compare dates with a String like "11-03-2015 23:17:53" rather than a Long like 1446585473561.

**Comment by vince-bickers** [comment]
The decision was taken to use this format because ISO-8601 formatted dates **are** sortable and hence comparable, plus they have the added advantage that they are immediately comprehensible as dates, while Longs are not. The fact that they are sortable like Longs means it is just as easy to select nodes or relationships based on timestamps and timestamp ranges in either format. The two advantages I see to the ISO-8601 format are that when looking at a date property on a node, we can see immediately it is meant to be a date - and also what that date is. More importantly when constructing Cypher queries that use literal date values in filter expressions, we can write an expression like this

```MATCH (n:Event) WHERE n.timestamp > '2015-11-03 ... '```

I would not like to have to write this expression and compute the equivalent long value each time.

That said, the ISO-8601 format may not be appropriate in all cases, and there are definitely going to be situations when using a Long would be preferable or even mandated. If you want or need to store Dates as Long values, you can simply annotate the Date field with @DateLong. You could also store the same Date value as both a Long and a String if you wanted - obviously at the cost of an extra property on the node or relationship.
