### ISSUE TITLE
Repository default load and save depth are not the same

### ISSUE THREAD

**Issue by jqp5000** [spring-projects/spring-data-neo4j#350]
```
groupId: org.springframework.data
artifactId: spring-data-neo4j
version: 4.1.2.RELEASE
```
The default depth of repository.findOne(id) is 1 and the default depth of repository.save(entity) is **-1**. This contradicts the suggestion made in the documentation: [Good Relationships: The Spring Data Neo4j Guide Book](http://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#reference_programming-model_detached_relating). This is currently causing issues and is not trivial to realize it.

> .... it’s strongly recommended to use depth consistently between load and save invocations. If you don’t then you may unexpectedly see relationships deleted or updates not persisting as you expect.

In my opinion if this is the intention then the documentation should specify it.

**Comment by luanne** [comment]
@jqp5000 sorry about this, that sentence from the documentation is not relevant any more. We'll remove it from the next version.
The default loading depth remains 1, and the save depth -1; this should not cause issues. Could you please report any issues you see due to this here: https://github.com/neo4j/neo4j-ogm/issues

Thanks!

**Comment by jqp5000** [comment]
Will do, thanks!
